Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Layout/LineLength:
  Max: 100
AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
